# Generated by Django 2.0.7 on 2018-08-28 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_auto_20180810_1024'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'permissions': (('view_cliente', 'Ver Cliente'),), 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
    ]
