# Generated by Django 2.0.7 on 2018-09-17 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_auto_20180828_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='banco_agencia',
            field=models.CharField(max_length=20, verbose_name='Agência'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='banco_conta',
            field=models.CharField(max_length=70, verbose_name='Conta'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='banco_operacao',
            field=models.CharField(max_length=120, verbose_name='Operação'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='mae',
            field=models.CharField(max_length=256, verbose_name='Nome da Mãe'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='pai',
            field=models.CharField(max_length=256, verbose_name='Nome do Pai'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], default='M', max_length=2),
        ),
    ]
