# Generated by Django 2.0.7 on 2018-08-08 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advogados', '0002_auto_20180808_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='sexo',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='sociedade',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='sociedade_cnpj',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
