# Generated by Django 2.0.7 on 2018-08-08 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advogados', '0003_auto_20180808_1654'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sociedade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=256)),
                ('cnpj', models.CharField(max_length=20)),
                ('endereco', models.CharField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='membro_de',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='advogados.Sociedade'),
            preserve_default=False,
        ),
    ]
