# Generated by Django 2.0.7 on 2018-08-08 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advogados', '0004_auto_20180808_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='membro_de',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='advogados.Sociedade'),
        ),
    ]
