# Generated by Django 2.0.7 on 2018-08-17 21:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advogados', '0005_auto_20180808_1757'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='sociedade',
            new_name='sociedade_nome',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='membro_de',
        ),
        migrations.AddField(
            model_name='sociedade',
            name='advogado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
