# Generated by Django 2.0.7 on 2018-08-28 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advogados', '0006_auto_20180817_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='sociedade',
            name='agencia',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='sociedade',
            name='banco',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='sociedade',
            name='conta',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='sociedade',
            name='oab',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
